---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tinyauth
  namespace: security
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tinyauth-secret
    creationPolicy: Owner
    template:
      data:
        # Pocket-ID OAuth provider
        PROVIDERS_POCKETID_CLIENT_ID: "{{ .TINYAUTH_CLIENT_ID }}"
        PROVIDERS_POCKETID_CLIENT_SECRET: "{{ .TINYAUTH_CLIENT_SECRET }}"
        OAUTH_WHITELIST: "{{ .TINYAUTH_OAUTH_WHITELIST }}"
  dataFrom:
    - extract:
        key: tinyauth
