---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${PUBLIC_DOMAIN/./-}"
  namespace: networking
spec:
  privateKey:
    rotationPolicy: Always
  secretName: "${PUBLIC_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${PUBLIC_DOMAIN}"
  duration: 1080h # 45d
  renewBefore: 240h # 10d before SSL will expire, renew it
  dnsNames:
    - "${PUBLIC_DOMAIN}"
    - "*.${PUBLIC_DOMAIN}"
