---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./agents.yaml
  - ./auth.yaml
  - ./chains.yaml
  - ./compress.yaml
  - ./ip.yaml
  - ./ratelimit.yaml
  - ./secure.yaml
