apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ratelimit
  namespace: networking
spec:
  rateLimit:
    average: 200
    burst: 300
    sourceCriterion:
      ipStrategy:
        depth: 1
