---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-crowdsec
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: crowdsec
  dependsOn:
    - name: cluster-apps-onepassword-store
  path: ./kubernetes/apps/security/crowdsec/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 1h
  targetNamespace: security
  timeout: 5m
  wait: false
