---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy-proxy-bouncer
  namespace: flux-system
spec:
  interval: 1h
  url: https://kdwils.github.io/envoy-proxy-crowdsec-bouncer
  timeout: 3m
