---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./metrics-server.yaml
  - ./external-dns.yaml
  - ./stakater.yaml
  - ./backube.yaml
  - ./piraeus.yaml
  - ./democratic-csi.yaml
  - ./lwolf-charts.yaml
  - ./projectcalico.yaml
  - ./crowdsec.yaml
  - ./envoy-proxy-bouncer.yaml
