---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./app-template.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./bitnami.yaml
  - ./external-dns.yaml
  - ./jetstack.yaml
  - ./stakater.yaml
  - ./prometheus-community.yaml
  - ./grafana.yaml
  - ./runix.yaml
  - ./kubereboot.yaml
  - ./ingress-nginx.yaml
  - ./backube.yaml
  - ./piraeus.yaml
  - ./external-secrets.yaml
  - ./jameswynn.yaml
  - ./democratic-csi.yaml
  - ./lwolf-charts.yaml
  - ./projectcalico.yaml
  - ./crowdsec.yaml
  - ./envoy-proxy-bouncer.yaml
