---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-gpt
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: democratic-csi-local-hostpath
  resources:
    requests:
      storage: 1Gi
