---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: pihole-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://mojo2600.github.io/pihole-kubernetes
  timeout: 2m0s
