---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates-import
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-onepassword-store
  interval: 1h
  path: ./kubernetes/apps/networking/certificates/import
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: networking
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates-export
  namespace: flux-system
spec:
  dependsOn:
    - name: certificates-import
    - name: cluster-apps-onepassword-store
  interval: 1h
  path: ./kubernetes/apps/networking/certificates/export
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: networking
  wait: false
