---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${PUBLIC_DOMAIN/./-}-tls"
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${PUBLIC_DOMAIN/./-}-tls"
    creationPolicy: Orphan
    template:
      type: kubernetes.io/tls
      metadata:
        annotations:
          cert-manager.io/alt-names: "*.${PUBLIC_DOMAIN},${PUBLIC_DOMAIN}"
          cert-manager.io/certificate-name: "${PUBLIC_DOMAIN/./-}"
          cert-manager.io/common-name: ${PUBLIC_DOMAIN}
          cert-manager.io/ip-sans: ""
          cert-manager.io/issuer-group: cert-manager.io
          cert-manager.io/issuer-kind: ClusterIssuer
          cert-manager.io/issuer-name: letsencrypt-production
          cert-manager.io/uri-sans: ""
        labels:
          controller.cert-manager.io/fao: "true"
  dataFrom:
    - extract:
        key: "${PUBLIC_DOMAIN/./-}-tls"
        decodingStrategy: Base64
