---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-paperless
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: paperless
  dependsOn:
    - name: cluster-apps-onepassword-store
    - name: cluster-apps-democratic-csi
  path: ./kubernetes/apps/default/paperless/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 1h
  targetNamespace: default
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-paperless-gpt
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: paperless-gpt
  dependsOn:
    - name: cluster-apps-onepassword-store
    - name: cluster-apps-democratic-csi
    - name: cluster-apps-paperless
  path: ./kubernetes/apps/default/paperless/gpt
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 1h
  targetNamespace: default
  timeout: 5m
  wait: false
