---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${CONF_CERT_ISSUER}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: ${CONF_CERT_ISSUER}
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-issuer-secret
              key: api-token
        selector:
          dnsZones:
            - "${PUBLIC_DOMAIN}"
