---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-tinyauth
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: tinyauth
  dependsOn:
    - name: cluster-apps-onepassword-store
  path: ./kubernetes/apps/security/tinyauth/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 1h
  targetNamespace: security
  timeout: 5m
  wait: false
