---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/referencegrant_v1beta1.json
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: crowdsec-bouncer-access
  namespace: networking
spec:
  from:
    # Allow SecurityPolicy from default namespace
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: default
    # Allow SecurityPolicy from security namespace
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: security
    # Allow SecurityPolicy from networking namespace
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: networking
    # Allow SecurityPolicy from observability namespace
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: observability
  to:
    - group: ""
      kind: Service
      name: crowdsec-bouncer-envoy-proxy-bouncer
