---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./actual/ks.yaml
  - ./wallos/ks.yaml
  - ./plex/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./homepage/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./bazarr/ks.yaml
  - ./subsyncarr/ks.yaml
  - ./calibre-web-automated/ks.yaml
  - ./resticprofile/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./maintainerr/ks.yaml
  - ./mealie/ks.yaml
  - ./paperless/ks.yaml
  - ./home-gallery/ks.yaml
