---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-onepassword-connect
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: onepassword-connect
  path: ./kubernetes/apps/external-secrets/onepassword-connect/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 1h
  targetNamespace: external-secrets
  timeout: 5m
  wait: false
