---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "${PUBLIC_DOMAIN/./-}-tls"
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: "${PUBLIC_DOMAIN/./-}-tls"
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: "${PUBLIC_DOMAIN/./-}-tls"
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: "${PUBLIC_DOMAIN/./-}-tls"
          property: *key
