---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  CLUSTER_POD_CIDR: "10.42.0.0/16"
  CLUSTER_SVC_CIDR: "10.43.0.0/16"
  CLUSTER_LB_CIDR: "192.168.0.0/16"

  CLUSTER_NODE_1_IP: "192.168.1.6"

  CONF_NFS_SRV_IP: "192.168.1.10"
  CLUSTER_LAN_NAS_IP: "192.168.1.10"

  LB_MEDIASERVER_IP: "192.168.1.20"
  LB_QBITTORRENT_IP: "192.168.1.21"
  LB_CALIBRE_WEB_IP: "192.168.1.22"
  LB_MAILRISE_IP: "192.168.1.25"
