---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  CLUSTER_LAN_CIDR: "192.168.0.0/16"
  CLUSTER_LAN_DOMAIN: "lan"
  CLUSTER_LAN_ROUTER_IP: "192.168.1.1"
  CLUSTER_SVC_LAN_DNS_IP: "192.168.1.2"
  CLUSTER_SVC_MEDIASERVER_IP: "192.168.1.3"
  CLUSTER_HOST1_IP: "192.168.1.6"
  CLUSTER_LAN_NAS_IP: "192.168.1.10"
  CLUSTER_SVC_INGRESS_CONTROLLER_IP: "192.168.1.20"
  CLUSTER_SVC_JELLYFIN_IP: "192.168.1.21"
  CLUSTER_SVC_SMTP_GATEWAY_IP: "192.168.1.24"
  CLUSTER_SVC_HOMEASSISTANT_IP: "192.168.1.50"
  CLUSTER_SVC_MQTT_IP: "192.168.1.51"
