---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./metallb/ks.yaml
  - ./ingress-nginx/ks.yaml
  # - ./cloudflared/ks.yaml
  # - ./external-dns/ks.yaml
  # - ./whoami/ks.yaml
