---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-tigera-operator
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: tigera-operator
  path: ./kubernetes/apps/tigera-operator/tigera-operator/app
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  prune: false
  decryption:
    provider: sops
  postBuild:
    substituteFrom: []
  dependsOn:
    - name: flux
  interval: 1h
  targetNamespace: tigera-operator
  timeout: 5m
  wait: false
