---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./ocirepository.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
  - ./volsync.yaml
  - ./config/secret.sops.yaml

commonLabels:
  app.kubernetes.io/name: paperless-ngx
  app.kubernetes.io/instance: paperless-ngx

configMapGenerator:
  - name: paperless-scripts
    files:
      - config/removepdfpassword.py
  - name: paperless-seed-scripts
    files:
      - config/seed-metadata.sh

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
