---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-restic
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-restic-secret
    creationPolicy: Owner
    template:
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}/paperless'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
  dataFrom:
    - extract:
        key: volsync-restic
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: paperless
  namespace: default
spec:
  sourcePVC: paperless
  trigger:
    schedule: "0 2 * * *"  # 2 AM daily backup
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: paperless-restic-secret
    cacheCapacity: 2Gi
    volumeSnapshotClassName: democratic-csi-local-hostpath
    storageClassName: democratic-csi-local-hostpath
    moverSecurityContext:
      runAsUser: 10001
      runAsGroup: 10001
      fsGroup: 10001
    retain:
      hourly: 0
      daily: 14
      weekly: 4
      monthly: 3
      within: 7d
