---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie
  namespace: default
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mealie-secret
    creationPolicy: Owner
    template:
      data:
        # smtp2go
        SMTP_HOST: "{{ .SMTP_HOSTNAME }}"
        SMTP_PORT: "{{ .SMTP_PORT }}"
        SMTP_FROM_EMAIL: "{{ .SMTP_FROM }}"
        SMTP_USER: "{{ .SMTP_USER }}"
        SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
        SMTP_AUTH_STRATEGY: "TLS"

        # google
        # OPENAI_BASE_URL: "{{ .GEMINI_BASE_URL }}"
        # OPENAI_MODEL: "{{ .GEMINI_MODEL }}"
        # OPENAI_API_KEY: "{{ .GEMINI_API_KEY }}"

        # mistral
        OPENAI_BASE_URL: "{{ .MISTRAL_CHAT_BASE_URL }}"
        OPENAI_MODEL: "{{ .MISTRAL_CHAT_MODEL }}"
        OPENAI_API_KEY: "{{ .MISTRAL_API_KEY }}"

        # openRouter
        # OPENAI_BASE_URL: "{{ .OPENROUTER_BASE_URL }}"
        # OPENAI_MODEL: "{{ .OPENROUTER_MODEL }}"
        # OPENAI_API_KEY: "{{ .OPENROUTER_API_KEY }}"
  dataFrom:
    - extract:
        key: smtp2go
    - extract:
        key: mistral
