---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tandoor-restic
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tandoor-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}/tandoor'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
  dataFrom:
    - extract:
        key: volsync-restic
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: tandoor
  namespace: default
spec:
  sourcePVC: tandoor
  trigger:
    schedule: "0 0 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 5
    repository: tandoor-restic-secret
    cacheCapacity: 1Gi
    volumeSnapshotClassName: democratic-csi-local-hostpath
    storageClassName: democratic-csi-local-hostpath
    moverSecurityContext:
      runAsUser: 10001
      runAsGroup: 10001
      fsGroup: 10001
    retain:
      hourly: 0
      daily: 14
      weekly: 0
      monthly: 0
      within: 7d
