---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-grafana
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: grafana
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack
    - name: cluster-apps-onepassword-store
  path: ./kubernetes/apps/observability/grafana/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 1h
  targetNamespace: observability
  timeout: 5m
  wait: false
