---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: networking
spec:
  certificates:
    - secretName: "${PUBLIC_DOMAIN/./-}"
  defaultCertificate:
    secretName: "${PUBLIC_DOMAIN/./-}"
