---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/upgrade.cattle.io/plan_v1.json
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent
  namespace: system-upgrade
spec:
  serviceAccountName: system-upgrade-controller
  concurrency: 1
  jobActiveDeadlineSecs: 1800 # 30 minutes timeout for upgrade jobs
  nodeSelector:
    matchExpressions:
      - { key: node-role.kubernetes.io/control-plane, operator: DoesNotExist }
  prepare:
    image: rancher/k3s-upgrade
    args: ["prepare", "server"]
  upgrade:
    image: rancher/k3s-upgrade
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: "v1.35.0+k3s1"
