---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-crowdsec-bouncer
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: crowdsec-bouncer
  dependsOn:
    - name: cluster-apps-crowdsec
    - name: envoy-gateway
  path: ./kubernetes/apps/networking/crowdsec-bouncer/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 1h
  targetNamespace: networking
  timeout: 5m
  wait: false
